server:
  port: 8091
spring:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 10.222.29.209
    port: 5672
    username: root
    password: 83aeb88a
#
#
#spring.application.name=receipt-service
#
#management.endpoints.jmx.exposure.include=*
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#
#
## spring cloud access&secret config
## 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
#alibaba.cloud.access-key=****
#alibaba.cloud.secret-key=****
#
#mybatis.mapper-locations=classpath:mapper/*Mapper.xml
#mybatis.type-aliases-package=com.oocl.receiptservice.dao
#
#
